### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by hdr24** [hdr24/ProyectoProgramacion#1]
## HTML

- [x] Indice
- [x] Inicio de sesion
- [x] Registro
- [x] Pregunta
- [x] Perfil
- [x] Formula preguntas
- [x] Formula respuestas
- [x] Eventos
- [x] Crea eventos
- [x] Sobre nosotros
- [x] Administracion

## CSS

- [x] Indice
- [x] Inicio de sesion
- [x] Registro
- [x] Pregunta
- [x] Perfil
- [x] Formula preguntas
- [x] Formula respuestas
- [x] Eventos
- [x] Crea eventos
- [x] Sobre nosotros
- [x] Administracion

Java

- [x] Indice
- [x] Inicio de sesion
- [x] Registro
- [x] Pregunta
- [x] Perfil
- [x] Formula preguntas
- [x] Formula respuestas
- [x] Eventos
- [x] Crea eventos
- [x] Sobre nosotros
- [x] Administracion
